name: tic_tac_toe_lib
description: A sample command-line application.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.1.0

# Add regular dependencies here.
dependencies:
  quiver: ^3.2.1
  equatable: ^2.0.5
  # path: ^1.8.0

dev_dependencies:
  test: ^1.21.0
  lints: ^2.0.0
  build_runner: ^2.4.6
  mockito: ^5.4.2
