// Mocks generated by Mockito 5.4.2 from annotations
// in tic_tac_toe_lib/test/mocking/game_states_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'package:mockito/mockito.dart' as _i1;
import 'package:tic_tac_toe_lib/src/API/classes/game_observer.dart' as _i2;
import 'package:tic_tac_toe_lib/src/API/enums/game_event.dart' as _i3;
import 'package:tic_tac_toe_lib/tic_tac_toe_lib.dart';

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [GameObserver].
///
/// See the documentation for Mockito's code generation for more information.
class MockGameObserver extends _i1.Mock implements _i2.GameObserver {
  @override
  void onPlaceMark(Position pos) => super.noSuchMethod(
        Invocation.method(
          #onPlaceMark,
          [pos],
        ),
        returnValueForMissingStub: null,
      );
  @override
  void onGameOver(_i3.GameEvent? state) => super.noSuchMethod(
        Invocation.method(
          #onGameOver,
          [state],
        ),
        returnValueForMissingStub: null,
      );
}
